name: Deploy App

on:
  push:
    branches:
      - main   # Se ejecuta al hacer push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configura Node.js (cambia versión si hace falta)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compila la app
      - name: Build app
        run: npm run build
        env:
          VITE_API_EMAILJS_TOKEN: ${{ secrets.VITE_API_EMAILJS_TOKEN }}   # ✅ así pasas el secret al entorno

      # 5. Opcional: crear un archivo .env (si tu framework lo necesita)
      - name: Create .env file
        run: |
          echo "VITE_API_EMAILJS_TOKEN=${{ secrets.VITE_API_EMAILJS_TOKEN }}" >> .env
